### ISSUE TITLE
Abcdesktop is not deployable on Kubernetes clusters.

### ISSUE THREAD

**Issue by mike-matera** [abcdesktopio/conf#1]
Hello! 

I have a Kubernetes cluster built using [microk8s](https://microk8s.io/). After following the Kubernetes instructions I find that the `daemonset-pyos-*` container cannot start because they don't have access to the Docker socket:

```
MountVolume.SetUp failed for volume "volumesock" : hostPath type check failed: /var/run/docker.sock is not │
│  a socket file
```

This is expected because Docker is not the container runtime for my cluster. This problem will also prevent abcdesktop.io from running in any of the major cloud vendors, who do not use Docker for Kubernetes anymore.

**Comment by alexandredevely** [comment]
Hello Mike,

I confirm this issue. abcdesktop.io uses the docker unix socket.
You are completely right, pyos services open the /var/run/docker.sock  to read container images application.

Today the last supported release of kubenertes is 1.23.7 with the dockershim. 
# debian or ubuntu
apt-get install -y kubectl=1.23.7-00 kubeadm=1.23.7-00  kubelet=1.23.7-00  

The docker engine dependency will be removed in next release and the image metadata will be stored in the mongo database service.

I'm working hard to publish a beta release, with the support of kubernetes release 1.24.

Alexandre

**Comment by mike-matera** [comment]
Thank you for your hard work! I'm happy to test the release when it's ready.

**Comment by alexandredevely** [comment]
Hello mike,
After one year, the abcdesktop 3.0 is now stable, with the support of kubernetes release 1.24 and 1.27
See you
Alexandre
