### ISSUE TITLE
add app images 

### ISSUE THREAD

**Issue by sunyi000** [abcdesktopio/conf#2]
I found that if I do
`crictl inspecti abcdesktopio/nautilus.d > nautilus.json
`
the json file format is different from what is provided in this repository.

If I then `curl -X PUT...` the output json of `crictl inspecti `to the API manager endpoint the output is `null`, and therefore the application will not be added to abcdesktop.

However, if I use `docker inspect`, there is no problem.

The API manager endpoint seems only accept `docker inspect `output, but the documentation page mentions that it should accept both `crictl inspecti `and `docker inspect`.

Am I missing anything, do I need to tweak the json after crictl inspecti? Thanks for the help

**Comment by sunyi000** [comment]
another question is that If I want to expose the nvidia driver installed on host machine to application containers, do I need to use oc.user.nvidia instead?

I have nvidia driver installed on the nodes, and each application requires different cudatoolkit version, so the cudatoolkit is installed in the application container and the container needs to see the nvidia driver..

I have configured kubelet to use nvidia driver by modifying /etc/default/kubelet, and am still testing..

Thanks

**Comment by alexandredevely** [comment]
Hello Yi,

You don't need oc.user.nvidia.
You only need the image abcdesktopio/oc.user.ubuntu:3.0
If your kubernetes node uses nvidia driver, you can use CUDA.
I use nvidia-smi command line to make sure that nvidia device can be reach by application

Alexandre

**Comment by alexandredevely** [comment]
About the commands crictl inspecti and docker inspect
Both of them should work and return OCI format image.
abcdesktop accept the OCI format image as input.

I have to check the crictl inspecti format read by abcdesktop manager.
Thank you

**Comment by alexandredevely** [comment]
This issue is confirmed

**Comment by alexandredevely** [comment]
This issue is fixed, please pull docker.io/abcdesktopio/oc.pyos:3.0

In the abcdesktop.yaml file
in the kind: DaemonSet for pyos section
change the `imagePullPolicy` to `Always`
```
      - name : pyos
        imagePullPolicy: Always
        image: abcdesktopio/oc.pyos:3.0
```

Then apply the abcdesktop.yaml  and restart the daemonset-pyos
