### ISSUE TITLE
Sorry for Posting under issue

### ISSUE THREAD

**Issue by SrikanthSabade** [abcdesktopio/conf#5]
what is the starting point from which i can change the UI of abcdesktop..
Plaese help new to kubernetes

**Comment by alexandredevely** [comment]
Hello SrikanthSabade,

You can update the webmodule (html and js files).
Have a look to [https://github.com/abcdesktopio/webModules](https://github.com/abcdesktopio/webModules) it contains all web files

See you
Alexandre
